# Data Wrangling

> Exploring the Glassdoor job postings dataset to uncover valuable insights into job roles, industries, and salary trends. Starting with data cleaning to prepare the dataset for analysis by handling missing values, duplicates, and inconsistencies.

In [2]:
#Importing Libraries

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/data-science-job-posting-on-glassdoor/Uncleaned_DS_jobs.csv
/kaggle/input/data-science-job-posting-on-glassdoor/Cleaned_DS_Jobs.csv

## Structure Analysis

In [3]:
#reading the csv file
df = pd.read_csv("/kaggle/input/data-science-job-posting-on-glassdoor/Uncleaned_DS_jobs.csv")
df.shape

(672, 15)

In [4]:
# Randomly Sampled Data 

df.sample(10)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
451,451,Data Scientist,$69K-$116K (Glassdoor est.),By clicking continue you agree to Built In's P...,3.2,The Trade Desk\n3.2,"Boulder, CO","Ventura, CA",1001 to 5000 employees,2009,Company - Public,Internet,Information Technology,Unknown / Non-Applicable,-1
650,650,"Scientist / Group Lead, Cancer Biology",$92K-$155K (Glassdoor est.),"Scientist / Group Lead, Cancer Biology\nLocati...",-1.0,Monte Rosa Therapeutics,"Cambridge, MA",-1,-1,-1,-1,-1,-1,-1,-1
386,386,Market Research Data Scientist,$110K-$163K (Glassdoor est.),"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck\n3.8,"Denver, CO","Denver, CO",51 to 200 employees,2009,Company - Private,Advertising & Marketing,Business Services,$10 to $25 million (USD),"Nielsen, Zappi, SurveyMonkey"
263,263,Associate Data Scientist,$91K-$150K (Glassdoor est.),Puget Sound Energy is looking to grow our comm...,3.3,Puget Sound Energy\n3.3,"Bothell, WA","Bellevue, WA",1001 to 5000 employees,1999,Company - Private,Utilities,"Oil, Gas, Energy & Utilities",$2 to $5 billion (USD),-1
518,518,Data Science Software Engineer,$212K-$331K (Glassdoor est.),We love programming and the excitement that co...,4.8,Klaviyo\n4.8,"Boston, MA","Boston, MA",201 to 500 employees,2012,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
181,181,Jr. Business Data Analyst (position added 6/12...,$56K-$97K (Glassdoor est.),April 2020 Update from WebFX: We're still acti...,4.7,webfx.com\n4.7,"Harrisburg, PA","Harrisburg, PA",201 to 500 employees,1997,Company - Private,Advertising & Marketing,Business Services,$25 to $50 million (USD),-1
325,325,Data Engineer,$79K-$147K (Glassdoor est.),About Rocket Lawyer\nWe believe everyone deser...,4.4,Rocket Lawyer\n4.4,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Private,Computer Hardware & Software,Information Technology,$50 to $100 million (USD),-1
237,237,Data Scientist,$71K-$123K (Glassdoor est.),Who we are\n\n\nFueled by a fundamental belief...,3.8,PayPal\n3.8,Texas,"San Jose, CA",10000+ employees,1998,Company - Public,Internet,Information Technology,$10+ billion (USD),"Square, Amazon, Apple"
580,580,"Vice President, Biometrics and Clinical Data M...",$138K-$158K (Glassdoor est.),"At Alector, our mission is to develop therapie...",4.8,Alector\n4.8,"South San Francisco, CA","South San Francisco, CA",51 to 200 employees,2013,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1
232,232,Data Scientist,$71K-$123K (Glassdoor est.),"Headquartered in Lynchburg, Va., BWX Technolog...",3.3,BWX Technologies\n3.3,"Oak Ridge, TN","Lynchburg, VA",5001 to 10000 employees,1850,Company - Public,Aerospace & Defense,Aerospace & Defense,$500 million to $1 billion (USD),-1

In [5]:
# Total Columns in the DataFrame

cols = df.columns
cols

Index(['index', 'Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

In [6]:
# Overview of Data Types 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              672 non-null    int64
 1   Job Title          672 non-null    object
 2   Salary Estimate    672 non-null    object
 3   Job Description    672 non-null    object
 4   Rating             672 non-null    float64
 5   Company Name       672 non-null    object
 6   Location           672 non-null    object
 7   Headquarters       672 non-null    object
 8   Size               672 non-null    object
 9   Founded            672 non-null    int64
 10  Type of ownership  672 non-null    object
 11  Industry           672 non-null    object
 12  Sector             672 non-null    object
 13  Revenue            672 non-null    object
 14  Competitors        672 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 78.9+ KB

## Data Wrangling
> * Removing Unnecessary Columns
> * Checking for duplicate values
> * Transforming missing or incomplete Data
> * Inspecting Data Types 
> * Formatting Columns for further Exploratory Analysis

In [7]:
## Removing unnecessary columns

df.drop(columns=['Job Description','Headquarters'],inplace=True)

In [8]:
#Checking for any duplicated record 

df.duplicated().sum()   #resulted in no duplicated values

0

In [ ]:
# Inspecting Column by Column for any possible transformation


# Column : Job Title


df['Job Title'].value_counts() #Categorically splitting up the column

In [ ]:
pd.set_option('display.max_rows',None) 
# Due to large number of cteogories, pandas view option is modified to display all results

df['Job Title']

In [ ]:
#Script to categorize data

#function categorization takes each row of Job Title Column and 
# based on the logic converts them into 3 categories


def categorization(title):
    title = title.lower() 
    if "data scientist" in title:
        return "Data Scientist"
    elif "analytics" in title:
        return "Analyst"
    elif "engineer" in title:
        return "Engineer"
    else:
        return "Other"


df['job_category'] = df['Job Title'].apply(categorization) # creating a new feature upon applying the function

df['job_category'].value_counts() #checking the new categories

In [ ]:
# column  : Salary estimate


df['Salary Estimate'][:5] #top 5 row values

In [ ]:
# Transforming the Salary Estimate Column to numerical data from Categorical

df['Salary'] = df['Salary Estimate'].str.split('-').str[0]   #splitting the data from a delimiter 

#only the 0th index value is stored in the new column

#succesfully extracted the lower bounded values from the data




df['Salary']= df['Salary'].str.replace('$',"").str.replace('K', " ").astype('int') # String Values are replaced with blanks

#Further, the text data is converted to numerical values

In [ ]:
#Column : Location 

#Splitting up the states from the cities 
# Broadly Categorizing data helps in Geospatial Analysis

df['State'] = df['Location'].str.split(',').str[1].str.strip()
#String is splitted from a blank space 
# The returning string value is stripped of any white spaces for efficient storage

In [ ]:
#Cleanup of ownership column(Categorical)

df['Type of ownership'].value_counts()

In [ ]:

# Putting the Strings in Correct format for easier analysis

# The function :
# 1. in case of a boolean match splits tthe strings and returns the values in the 1st index 
# 2. in case of a mismatch it defaults 

def change(values):
    if 'Company' in values:
        company,v = values.split('-')
        return v
    else:
        return 'Others'


#Modifyiing the original Column 
df['Type of ownership'] = df['Type of ownership'].apply(change)

In [ ]:
df['Type of ownership'].value_counts()  #Succesfull Transformation

In [ ]:
## Column : sectors(Categorical)


# Enhanced code readability with lambda function, gracefully handling the null values 

df['Sector'] = df['Sector'].apply(lambda x: 'Others' if x== -1 else x)

In [ ]:

#Column : Company Name


#removed the new line character from the Company Name enhancing readability

def name_change(values):
    if '\n' in values:
        return values.replace("\n","")


df['Company Name'].apply(name_change)

In [ ]:
##dropping unnecessary columns and renaming the necessities

df.drop(columns=['index','Job Title','Salary Estimate','Location'], inplace=True)

## End of Data Wrangling

In [ ]:

#Exporting the new Data Frame for Analysis

df.to_csv("JobLists.csv",index=False)  #stores the csv file in the current working directory